name: coach
author: Isaac Jessup
email: ibjessup@gmail.com
url: https://github.com/ggpwnkthx
version: '0.1'
title: 'Cluster of Arbitrary Cheap Hardware'
icon: futbol
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - 'resources/js/module.es'
    - 'ng:ajenti.coach'
